import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';

const EXAMS_DIR = path.join(process.cwd(), 'src/content/exams');
const OUTPUT_FILE = path.join(process.cwd(), 'src/data/generated-exams.ts');

async function generateExams() {
    if (!fs.existsSync(EXAMS_DIR)) {
        console.log('No exams directory found.');
        return;
    }

    const exams = {};

    // Recursive function to walk directories
    function walkDir(dir) {
        const files = fs.readdirSync(dir);
        for (const file of files) {
            const filePath = path.join(dir, file);
            const stat = fs.statSync(filePath);
            if (stat.isDirectory()) {
                walkDir(filePath);
            } else if (file.endsWith('.md')) {
                const content = fs.readFileSync(filePath, 'utf8');
                try {
                    // Parse frontmatter
                    const { data, content: markdownBody } = matter(content);
                    if (!data.id) {
                        console.warn(`Skipping ${file}: Missing id in frontmatter`);
                        continue;
                    }

                    // Helper to extract verify and setup blocks
                    const extractScripts = (md) => {
                        const verifyRegex = /```verify\n([\s\S]*?)\n```/g;
                        const setupRegex = /```setup\n([\s\S]*?)\n```/g;

                        let verifyScript = '';
                        let setupScript = '';

                        let cleanMd = md.replace(verifyRegex, (match, script) => {
                            verifyScript += script + '\n';
                            return ''; // Remove from display
                        });

                        cleanMd = cleanMd.replace(setupRegex, (match, script) => {
                            setupScript += script + '\n';
                            return ''; // Remove from display
                        });

                        return { cleanMd, verifyScript, setupScript };
                    };

                    // Split tasks for randomization
                    // We look for "# Task" at the start of a line
                    const parts = markdownBody.split(/^# Task /m);
                    const introMarkdown = parts[0];
                    // Re-add the header back to the tasks
                    const rawTasks = parts.slice(1).map(t => '# Task ' + t);

                    const parsedTasks = rawTasks.map(t => {
                        const { cleanMd, verifyScript, setupScript } = extractScripts(t);
                        return { markdown: cleanMd, verify: verifyScript, setup: setupScript };
                    });

                    const finalTasks = parsedTasks.length > 0 ? parsedTasks : [];

                    // Ensure ID is a string
                    const lessonId = String(data.id);

                    // Parse the intro markdown to extract any setup/verify blocks that might be there
                    const { cleanMd: cleanIntro, verifyScript: introVerify, setupScript: introSetup } = extractScripts(introMarkdown);

                    // Determine the main setup script
                    // If we found one in the intro, use it.
                    let mainSetup = introSetup;

                    // If no explicit setup script, try to auto-detect based on content
                    if (!mainSetup) {
                        const hasCrictl = markdownBody.includes('crictl');
                        const hasKubectl = markdownBody.includes('kubectl');

                        if (hasCrictl) {
                            mainSetup = 'echo "Environment Ready (Auto-generated)"\n';
                        } else if (hasKubectl) {
                            mainSetup = 'echo "Environment Ready (Auto-generated)"\n';
                        } else {
                            mainSetup = 'echo "Environment Ready"\n';
                        }
                    }

                    // Use introVerify if available, otherwise fallback to empty or handle strictly
                    const mainVerify = introVerify;

                    exams[lessonId] = {
                        ...data,
                        id: lessonId,
                        markdown: cleanIntro, // Changed from mainMarkdown (full) to cleanIntro (split)
                        verifyScript: mainVerify,
                        setupScript: mainSetup,
                        tasks: finalTasks,
                    };
                } catch (e) {
                    console.error(`Error parsing ${file}:`, e);
                }
            }
        }
    }

    walkDir(EXAMS_DIR);

    const fileContent = `// Auto-generated by scripts/generate-exams.mjs
import { Lesson } from './types';

export const generatedExams: Record<string, Lesson> = ${JSON.stringify(exams, null, 2)};
`;

    fs.writeFileSync(OUTPUT_FILE, fileContent);
    console.log(`Generated ${Object.keys(exams).length} exams to ${OUTPUT_FILE}`);
}

generateExams();
