import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';

const EXAMS_DIR = path.join(process.cwd(), 'src/content/exams');
const OUTPUT_FILE = path.join(process.cwd(), 'src/data/generated-exams.ts');

async function generateExams() {
    if (!fs.existsSync(EXAMS_DIR)) {
        console.log('No exams directory found.');
        return;
    }

    function getFiles(dir) {
        const dirents = fs.readdirSync(dir, { withFileTypes: true });
        const files = dirents.map((dirent) => {
            const res = path.resolve(dir, dirent.name);
            return dirent.isDirectory() ? getFiles(res) : res;
        });
        return Array.prototype.concat(...files);
    }

    const files = getFiles(EXAMS_DIR);
    const exams = {};

    for (const filePath of files) {
        if (!filePath.endsWith('.md')) continue;

        const content = fs.readFileSync(filePath, 'utf-8');
        const { data, content: markdown } = matter(content);

        if (!data.id) {
            console.warn(`Skipping ${filePath}: Missing id in frontmatter`);
            continue;
        }

        exams[data.id] = {
            id: data.id,
            title: data.title || 'Untitled Exam',
            category: data.category || 'CKA',
            duration: data.duration || '120 mins',
            markdown: markdown
        };
    }

    const fileContent = `// Auto-generated by scripts/generate-exams.mjs
import { Lesson } from './lessons';

export const generatedExams: Record<string, Lesson> = ${JSON.stringify(exams, null, 2)};
`;

    fs.writeFileSync(OUTPUT_FILE, fileContent);
    console.log(`Generated ${Object.keys(exams).length} exams to ${OUTPUT_FILE}`);
}

generateExams();
