// Auto-generated by scripts/generate-exams.mjs
import { Lesson } from './lessons';

export const generatedExams: Record<string, Lesson> = {
  "cka-mock-auto-01": {
    "id": "cka-mock-auto-01",
    "title": "Automated CKA Mock Exam 1",
    "category": "CKA",
    "duration": "120 mins",
    "markdown": "\n# Task 1: Create a Pod\nCreate a pod named `nginx` with image `nginx`.\n\n```bash\nkubectl run nginx --image=nginx\n```\n\n# Task 2: Service Limit\nCreate a service named `my-service` of type `NodePort`.\n"
  }
};
